Add: Typing Sound Audio Bus in Character Settings
dialogic-godot/dialogic pull request #2425
Opened 2024-10-03 19:51 UTC by anis-mahsoume

Add a new field "Audio Bus" into the character settings typing sounds section:
![image](https://github.com/user-attachments/assets/f0627b98-1684-4782-8dae-1e66838fb512)
The Audio Bus is an OptionButton field which values are populated from AudioServer buses.

2024-10-10 13:09 UTC, CakeVR requested changes
Just some minor improvements, you can simply apply all of them.

Thanks for your Pull Request.

2024-10-10 13:09 UTC, CakeVR commented on addons/dialogic/Modules/Text/character_settings/character_moods_settings.gd
> +	for i in AudioServer.bus_count:
```suggestion
	for i: int in AudioServer.bus_count:
```

2024-10-10 13:09 UTC, CakeVR commented on addons/dialogic/Modules/Text/character_settings/character_moods_settings.tscn
> +tooltip_text = "Audio bus in which the type sounds will be sent"
```suggestion
tooltip_text = "Audio bus on which the typing sounds will be played."
```

2024-10-10 13:09 UTC, CakeVR commented on addons/dialogic/Modules/Text/node_type_sound.gd
>  	if !enabled or (get_parent() is DialogicNode_DialogText and !get_parent().enabled):
```suggestion
	bus = AudioServer.get_bus_name(bus_index)
	
	if !enabled or (get_parent() is DialogicNode_DialogText and !get_parent().enabled):
```

2024-10-10 14:56 UTC, anis-mahsoume commented
> Just some minor improvements, you can simply apply all of them.
> 
> Thanks for your Pull Request.

Thanks @CakeVR for your review: I have applied the changes you suggested.

2024-10-11 06:11 UTC, CakeVR commented
The problem I have with this solution is that you use `_on_started_revealing_text` to set the Audio Bus which gets triggered every single text message.

I don't think this is a good solution.

2024-10-18 09:16 UTC, Jowan-Spooner commented
I don't think this should be a setting in the character editor, rather a global setting or a style setting. I cannot see a use-case where you'd need to change this per type sound mood.

2024-11-11 07:04 UTC, CakeVR commented
Hello, is there any interest in continuing on this PR?
As I agree with Jowan, there would have to be Global Setting in the Settings tab instead.

2024-11-11 10:56 UTC, anis-mahsoume commented
Hi,
This issue has been fixed in
https://github.com/dialogic-godot/dialogic/pull/2456
So closing this PR

2024-11-11 10:56 UTC, closed without merging