Add Character Prefixes and Suffixes to Text Events
dialogic-godot/dialogic pull request #2460
Opened 2024-10-29 04:43 UTC by CakeVR

This new Feature allows to set text segments before and after a text spoken by a character.

For instance, you can set the `“` or `"` for your quotation marks or use rich tags, such as colour.

2024-10-29 19:25 UTC, salianifo requested changes
This is such a handy feature!

2024-10-29 19:25 UTC, salianifo commented on addons/dialogic/Editor/CharacterEditor/character_prefix_suffix.tscn
> +tooltip_text = "Mood name"
```suggestion
```

2024-10-29 19:25 UTC, salianifo commented on addons/dialogic/Editor/CharacterEditor/character_prefix_suffix.tscn
> +tooltip_text = "Mood name"
```suggestion
```

2024-11-11 16:50 UTC, Jowan-Spooner commented
I very much like this. 
I'd remove the placeholder quotation marks in the line edits, because with just a symbol it's a bit unclear that it's a placeholder.

I'd also recommend doing it like this:
```gdscript
	if current_character:
		var character_prefix: String = current_character.custom_info.get(DialogicCharacterPrefixSuffixSection.PREFIX_CUSTOM_KEY, DialogicCharacterPrefixSuffixSection.DEFAULT_PREFIX)
		var character_suffix: String = current_character.custom_info.get(DialogicCharacterPrefixSuffixSection.SUFFIX_CUSTOM_KEY, DialogicCharacterPrefixSuffixSection.DEFAULT_SUFFIX)
		text = character_prefix + text + character_suffix
					
	text_node.reveal_text(text, additional)
```
Because this way the modified version is what is getting returned by `Dialogic.Text.update_dialog_text()` and thus also what is stored in the simple history.

Or is there a reason you didn't do it that way?

2024-11-11 17:08 UTC, CakeVR commented
> I very much like this. I'd remove the placeholder quotation marks in the line edits, because with just a symbol it's a bit unclear that it's a placeholder.
> 
> I'd also recommend doing it like this:
> 
> ```gdscript
> 	if current_character:
> 		var character_prefix: String = current_character.custom_info.get(DialogicCharacterPrefixSuffixSection.PREFIX_CUSTOM_KEY, DialogicCharacterPrefixSuffixSection.DEFAULT_PREFIX)
> 		var character_suffix: String = current_character.custom_info.get(DialogicCharacterPrefixSuffixSection.SUFFIX_CUSTOM_KEY, DialogicCharacterPrefixSuffixSection.DEFAULT_SUFFIX)
> 		text = character_prefix + text + character_suffix
> 					
> 	text_node.reveal_text(text, additional)
> ```
> 
> Because this way the modified version is what is getting returned by `Dialogic.Text.update_dialog_text()` and thus also what is stored in the simple history.
> 
> Or is there a reason you didn't do it that way?

Thanks! I have applied your suggestions.

2024-11-11 17:24 UTC, Jowan-Spooner commented
Cool. Looks good to me now!

2024-11-11 17:24 UTC, merged